name: second project
on: workflow_dispatch
jobs:
  
  Lint:
    runs-on: ubuntu-lastest
    steps:
      - name: get the code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run Lint
        run:  npm run lint

  Test:
    needs: Lint
    runs-on: ubuntu-lastest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install dependencies
        run:  npm ci
      - name: Run tests
        run : npm test
  
  Deploy:
    needs: Test
    runs-on: ubuntu-lastest
    steps:
      - name : get the code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run : npm run build 
      - name: Deploy
        run : echo "Deployinggg"