name : Second Project
on: workflow_dispatch
jobs:
  Lint:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job == 'all' || github.event.inputs.job == 'Lint' }}
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install dependencies
        run : npm ci
      - name : Run Lint 
        run : npm run lint 
  
  Test:
    needs: Lint
    runs-on: ubuntu-latest
    if: ${{ github.event.imputs.job == 'all' || github.event.inputs.job == 'Test'}}
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run Test 
        run : npm test 
  
  Deploy:
    needs: Test
    runs-on: ubuntu-latest
    if: ${{ github.events.inputs.job =='all' || github.event.inputs.job == 'Deploy'}}
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run : npm run build 
      - name : Deploy 
        run : echo " Deployingggg....."