name: Handle Issue
on : 
  issues:
    types:
      - opened
jobs:
  Issue:
    runs-on: ubuntu-latest
    steps:
      - name: handle issues 
        run: echo "{{ toJSON(github.event) }}"
  
  Secret:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: keeping env sec
        run : echo " Hello Kiran , your pin is $SECRET "
    env:
      SECRET : ${{secrets.SECRET}}